version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet -d wallet"]
      interval: 5s
      timeout: 3s
      retries: 10
  api:
    build: .
    env_file: .env
    depends_on: [postgres]
    ports: ["3000:3000"]
    command: ["npm","run","start:prod"]
volumes:
  pgdata:
