apiVersion: v1
kind: Service
metadata:
  name: wallet-api
  labels: { app: wallet-api }
spec:
  type: LoadBalancer
  selector: { app: wallet-api }
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  